### ISSUE TITLE
Catch exception connected with disabled Redis configuration option

### ISSUE THREAD

**Issue by evgeny-s** [zhchsf/redis_cluster#2]
Hello. 

Would be great to add handling of cluster disabled option of Redis instance here:
https://github.com/zhchsf/redis_cluster/blob/master/lib/redis_cluster/client.rb#L52

Because if you have not configure your Redis to cluster, there is not obvious error here.

Let me know if you need more explanations.

Thank you for your work!

**Comment by zhchsf** [comment]
Sorry i see you issue yesterday.

Do you mean this?
https://github.com/zhchsf/redis_cluster/blob/issue2/lib/redis_cluster/client.rb#L64

**Comment by evgeny-s** [comment]
Yes I had this issue but I didn't get proper error message.

**Comment by zhchsf** [comment]
If raise error for one node, It has some problems when app is running and you delete node from cluster.
So now it will raise error only when cluster initialize .
The codes is pending merged.

**Comment by zhchsf** [comment]
merged!

**Comment by evgeny-s** [comment]
ok. Thank you.
