### ISSUE TITLE
Support for pipelined

### ISSUE THREAD

**Issue by rolandhawk** [zhchsf/redis_cluster#4]
Hi

Could you add support for pipelining in redis cluster?

Thank you.

**Comment by zhchsf** [comment]
Yes, give me some times!

**Comment by zhchsf** [comment]
Please use version 0.2.7

Only support pipeline commands to one redis node once. You must ensure keys at one slot: use same key or hash tags.

For example:
```ruby
rs.pipelined do
  rs.set "{foo}one", 1
  rs.set "{foo}two", 2
end
```

**Comment by rolandhawk** [comment]
Do you have any plan to make it work for multiple node?

Thank you for your update anyway 👍. I will check it.

**Comment by zhchsf** [comment]
If some node can't connect or slot is migrating, client can't guarantee sequence of your commands, or maybe only some commands successed. It will generate great bugs for your business.

So recently i haven't plan support multiple nodes or slots. If has perfect solution, i will be try.

I will add feature to check if all keys at same slot when pipelined.

thanks
