### ISSUE TITLE
No Password protected support?

### ISSUE THREAD

**Issue by AbelLai** [zhchsf/redis_cluster#5]
I run six nodes with password protected. And run the example as below:
```ruby
hosts = [{host: '127.0.0.1', port: 7000}, {host: '127.0.0.1', port: 7001}]
rs = RedisCluster.new hosts
rs.set "test", 1
```
I got error: `Redis::CommandError: NOAUTH Authentication required`. So can we support the scenario like this?

**Comment by zhchsf** [comment]
use version 0.2.8
```ruby
RedisCluster.new hosts, password: 'password'
```

**Comment by AbelLai** [comment]
Sorry, I forgot to say thank you! Thanks, again!
