### ISSUE TITLE
EVAL command doesn't work

### ISSUE THREAD

**Issue by relonger** [zhchsf/redis_cluster#6]
in method
```
    def key_by_command(method, args)
      case method.to_s.downcase
      when 'info', 'exec', 'slaveof', 'config', 'shutdown'
        nil
      else
        return args.first
      end
    end
```
you use the first arg to select which node to use which isn't correct for eval command, where the first arg it the script itself. As the result you send command to invalid node, got MOVED response, reload nodes and retry again and again, failing after long pause.

I'v patched this method like this:
```
  def key_by_command(method, args)
      case method.to_s.downcase
      when 'eval'
        return args[1][0]
      when 'info', 'exec', 'slaveof', 'config', 'shutdown'
        nil
      else
        return args.first
      end
    end
```

and it worked fine now. However it should be fixed correctly to support eval without args and to support EVALSHA and other script commands.

**Comment by zhchsf** [comment]
thanks
please use version 0.2.9
```ruby
# script commands will run on all nodes
rs.script :load, "return redis.call('get', KEYS[1])"
rs.script :exists, '4e6d8fc8bb01276962cce5371fa795a7763657ae'
rs.script :flush

# eval/evalsha must executed at one node with hash tag keys in same slot
# and must use KEYS to fetch keys in lua script
rs.eval "return redis.call('get', KEYS[1]) + ARGV[1]", [:test], [3]
rs.evalsha '727fc2fb7c0f11ec134d998654e3dadaacf31a97', [:test], [5]

# if lua script don't depend on any keys and argvs, you also need execute with a key
rs.eval "return 'hello redis!'", [:foo]
```

**Comment by relonger** [comment]
Thank's. Will try soon.
FYI I made a port of your gem to Crystal language: https://github.com/relonger/crystal_redis_cluster
Please check if I have to consider some rules and license.

**Comment by zhchsf** [comment]
You don't need to consider any license. It can be used freely.
Thanks.
